### ISSUE TITLE
Banco de Imágenes para Tests

### ISSUE THREAD

**Issue by dprada** [TallerLIBI/an-lisis-movilidad#2]
Hola @RubiVega,

Sería bueno tener 4 o 5 imágenes como las que quieres analizar que nos funcione como banco de pruebas. ¿Podrías crear una carpeta aquí y subirlas antes de nuestra reunión? Si no puedes, al menos llevarlas en un usb esta tarde.

Un saludo

**Comment by RubiVega** [comment]
![553u-1112](https://user-images.githubusercontent.com/36717107/37434483-5c18b128-27a5-11e8-8fcf-679097d5cb46.jpg)
![647u-0712](https://user-images.githubusercontent.com/36717107/37434485-5c2c6650-27a5-11e8-8322-d7418ad026db.png)
![816u-1112](https://user-images.githubusercontent.com/36717107/37434486-5c42c986-27a5-11e8-9bc9-6160b1c2e9f7.jpg)
![cft073](https://user-images.githubusercontent.com/36717107/37434487-5c58fd82-27a5-11e8-8eee-d25e52e8b41b.jpg)
![img_20170421_151919](https://user-images.githubusercontent.com/36717107/37434488-5c80715a-27a5-11e8-876c-e277e94abce7.jpg)
![img_20170421_152920](https://user-images.githubusercontent.com/36717107/37434489-5cabf686-27a5-11e8-875a-9ae2c92ffae1.jpg)
![img_20170421_153355](https://user-images.githubusercontent.com/36717107/37434491-5cd3f91a-27a5-11e8-86cf-889b4564257a.jpg)
![img_20170421_154730](https://user-images.githubusercontent.com/36717107/37434492-5cf0d454-27a5-11e8-93ef-bbb460b57014.jpg)
